name: CI-dev-pipeline
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    permissions: 
        contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - postgres_version: 12
            alpine_postgres_version_string: ""
            alpine_image: "alpine:3.12"
            suffix: ""
          - postgres_version: 14
            alpine_postgres_version_string: "14"
            alpine_image: "alpine:3.19"
            suffix: "-14"
          - postgres_version: 15
            alpine_postgres_version_string: "15"
            alpine_image: "alpine:3.19"
            suffix: "-15"
    steps:
      - uses: actions/checkout@v4
      - name: Release
        if: ${{ matrix.postgres_version == 12 }}
        uses: crowbarmaster/GH-Automatic-Releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            README.md

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=auto
            suffix=${{ matrix.suffix }}
          tags: |
            type=semver,pattern={{version}},suffix=${{ matrix.suffix }}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ matrix.suffix }}
            type=semver,pattern={{major}},suffix=${{ matrix.suffix }}
            type=edge,enable=true,suffix=${{ matrix.suffix }}
          images: richardwiden/postgresql-client

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          build-args: |
            "BASE_IMAGE=${{matrix.alpine_image}}
            "POSTGRES_VERSION=${{ matrix.alpine_postgres_version_string }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Update repo description
        if: ${{ matrix.postgres_version == 12 }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: richardwiden/postgresql-client
          readme-filepath: ./README.md